### PR TITLE
fix(org): update load, declare-function

### PR DESCRIPTION
**Pull request by bdarcus**
In Emacs 31, org-element-property and org-element-type has been moved to a new file: org-element-ast.

Update code to handle this properly, depending on version.

### CODE REVIEW

**Comment by bdarcus** [comment]
@yantar92 - this little PR is me trying to update citar to accommodate you moving a couple of functions to `org-element-ast`, but my CI is complaining about the code I have here. Any suggestions for fixing it?

**Comment by yantar92** [comment]
Update https://github.com/emacs-citar/citar/blob/main/citar-org.el#L31

**Comment by bdarcus** [comment]
Right, but how do I do it conditionally? I still have to use `org-element` for earlier versions.

**Comment by yantar92** [comment]
I suspect that you cannot do it conditionally. You may consider using ext:, which will suppress CI failures.

**Pull request closed without merging**
