### PR TITLE
Generalize `citar--shorten-names` + add display transform function for full names

### PR DESCRIPTION
**Pull request by torfjelde**
Generalizes citar--shorten-names + implements rendering of full names as discussed in #805.

Replaces #807 as I did not follow the contribution guidelines in #807.

### CODE REVIEW

**Comment by torfjelde** [comment]
@bdarcus are there any tests for this stuff?

**Comment by bdarcus** [comment]
> are there any tests for this stuff?

Do you mean in this project, or more generally?

If the former, this is an example (see #780) where we should probably add some.

**Comment by torfjelde** [comment]
For the project, and specifically of the display transform functions:)

But aight; should I just make a new `ert-deftest` for the short- and full-name methods? Are there an existing list of author names that I could maybe draw from as test-cases, or should I add some?

**Comment by bdarcus** [comment]
> Are there an existing list of author names that I could maybe draw from as test-cases, or should I add some?

There isn't, but I can give you an example of a key type that I included when developing the existing function; a corporate (organizational) name:

```
World Bank
```

That shouldn't be shortened.

Though you shouldn't worry about it, you should be aware of the discussion here:

https://github.com/emacs-citar/citar/issues/532

**Comment by bdarcus** [comment]
So what do we want to do with this, given @aikrahguzar's alternative?

https://github.com/emacs-citar/citar/issues/805#issuecomment-1783892531

**Comment by bdarcus** [comment]
> So what do we want to do with this, given @aikrahguzar's alternative?
> 
> [#805 (comment)](https://github.com/emacs-citar/citar/issues/805#issuecomment-1783892531)

I'm going to close this, and we can consider @aikrahguzar's alernative.

**Pull request closed without merging**
