### PR TITLE
refactor: cache the parsebib hashes

### PR DESCRIPTION
**Pull request by bdarcus**
Experimenting, per discussion on #623.

----------

Rather than caching the 'completing-read' candidates, instead cache the
hashes created by 'parsebib-parse'.

Change the API a bit to focus on using keys to access the data.

----------

## TODO

- [X] modify caches and `citar--get-candidates`, now renamed `citar--get-data`
- [X] adapt `citar--get-entry` and `citar--get-value`
- [ ] adapt `citar--format-candidates`
- [ ] add functions to update metadata in the cached hash

### CODE REVIEW

**Comment by aikrahguzar** [comment]
The assumption in #623 that the bibtex-parsing is slow part of candidate generation is not accurate. In my experience the time is spent almost equally between bibtex parsing and formatting the candidates. Here is a time profile of `citar-refresh` for a file with about 1500 entries: 
citar-profile

So I this will hurt performance and we can't take advantage of the one advantage of not caching the formatted candidates: the ability to adapt to different frame widths. We specify the number of characters in each field absolutely and not relative to the frame widths so if the frame width changes the candidates are still going to look the same except for one field and they might get truncated.

That said the actual issue in #623  is pretty narrow: it basically only pertains to the `candidate-hidden` part of the entry and that doesn't seem to be the expensive part of the operation (though as my entries don't have notes or files or links, it is also mostly empty for me. Someone with lots of notes should check the actual impact, but it involves no expensive string manipulation so I think it will probably not contribute much). So to me the better way would be to pre-compute everything that can be deduced from the bibtex file including the formatted candidate string and then invisibly append `has-file` etc on the fly.

**Comment by bdarcus** [comment]
OK, so I'll close this then :-)

> That said the actual issue in https://github.com/emacs-citar/citar/issues/623 is pretty narrow: it basically only pertains to the candidate-hidden part of the entry.

And the related affixations.

> So to me the better way would be to pre-compute everything that can be deduced from the bibtex file including the formatted candidate string and then invisibly append `has-file` etc on the fly.

Is that basically status quo? Or are you suggesting some change?

My example here was using a predicate function against the "pre-computed" data.

https://github.com/emacs-citar/citar/issues/623#issuecomment-1146492476

**Comment by bdarcus** [comment]
To provide context to that, I was wanting to add a defcustom to allow pre-filtering of candidates for `citar-open-notes` and `citar-open-files`. So just wanted that to be snappy.

**Comment by aikrahguzar** [comment]
> Is that basically status quo? Or are you suggesting some change?
> 
> My example here was using a predicate function against the "pre-computed" data.
> 
> [#623 (comment)](https://github.com/emacs-citar/citar/issues/623#issuecomment-1146492476)

I don't completely understand the issues in #623 but my impression is that motivating this change is the fact that the notes and associated files can change even without the bib files changing. What I am saying is that issue can be resolved by keeping the pre-computation of the candidate strings against the format but not pre-computing the invisible "has-file" "has-notes" etc. This part is recomputed every time `citar--get-candidates` is called. With this approach we longer need to invalidate the cache if a note or file is added/removed. But I am unsure how expensive doing this actually is since I don't have notes/files.

**Comment by bdarcus** [comment]
> my impression is that motivating this change is the fact that the notes and associated files can change even without the bib files changing. 

And the UI may not align with what, for example, `citar-has-note` reports.

> What I am saying is that issue can be resolved by keeping the pre-computation of the candidate strings against the format but not pre-computing the invisible "has-file" "has-notes" etc. 

Here I'm not following. Can you restate?

Also, FYI, in #595 I added conses for notes and files to the cached entry data list. This was a simple change to the `citar-format-candidates` function.

In #623, I was just saying it made more sense to use that cached data, than to use the functions that create that data, to ensure the alignment I mentioned above.

> This part is recomputed every time `citar--get-candidates` is called. With this approach we longer need to invalidate the cache if a note or file is added/removed. But I am unsure how expensive doing this actually is since I don't have notes/files.

I _think_ maybe you're saying something similar here to https://github.com/emacs-citar/citar/issues/623#issuecomment-1146511688 ("Or perhaps include the string representation in the cache, but tack on the note and file indicators as-needed")?

In https://github.com/emacs-citar/citar/issues/623#issuecomment-1146589524, I was experimenting with basically that idea, and was planning to add it here. But I hadn't gotten that far on the details.

**Comment by roshanshariff** [comment]
@aikrahguzar, thanks for the profile data! In this case, I agree that we can't recompute the string formatting every time and we need to cache it.

I did indeed mean that we could cache the parts of the candidate string that only depend on the bib file, i.e. everything but the invisible "has:note" and "has:string". There would still be some string concatenation to be done at the end, but should be much faster than actually doing the string template expansion from scratch.

That said, there's no urgency about any of this (and indeed I don't think there's likely to be a performance issue with the current implementation, because there shouldn't be a need to rescan the files/notes more than once per user operation). When I have some time I'll try implementing and benchmarking this proposal.

It occurred to me that we could also get the layout to be responsive to the window width without much more work: we'd format and cache two strings, one of unlimited length and another fixed-width string to be shown at the right margin. Then at display-time we could just truncate the first string to the required width and concatenate it with the second.

The truncation would be done with display properties (as by `truncate-string-to-width` with the `ELLIPSIS-TEXT-PROPERTY` argument) so that the hidden part of the text would remain searchable. I imagine that concatenating three strings instead of two is probably doable within the performance budget (i.e. the left column, right column, and invisible "has:note" and "has:file" tags).

**Comment by bdarcus** [comment]
A couple of random thoughts. 

And to be clear, I don't believe these are critical; I'd just like to settle at the first before I tag 1.0 soon, since it's an API question. The other stuff is just internal details.

In working on this, it seemed to me that some of the "get" and formstting-related functions that have `entry` as arg could instead use `citekey`. It's a small thing, but would it make sense to change those?

The other thing is really just a high-level observation, which became more clear to me as I was playing with this branch:

Generally, we have two kinds of data access we need, and which we want to be performant.

1. Key lookup of reference data
2. Formatted string lookup of key

2 is purely for the completion candidates, while 1 is for the rest.

I was just thinking about the general fact that hash-tables are much faster in large collections (someone [here](https://www.reddit.com/r/emacs/comments/75h7k4/comment/do6h0xm/)  notes `delete-dups` uses list when less than  100, but hash-tables otherwise).

So notwithstanding caching and stuff (which does complicate this a lot), but just from that high level POV, you could imagine two hash-tables that reflect that above distinction; one to use for completing-read, and the other for everything else.

The caveats are important though, including that it's expensive to create the candidate strings regardless.

**Comment by bdarcus** [comment]
PS - interesting performance detail of the formatted string:

In bibtex-completion, the candidate is a pre-forrnatted string; designed only for filtering, and NOT for display.

The formatting for display happens on-demand, in ivy and helm, which both allow that.

Completing-read doesn't, unless you count the new grouping support.

**Comment by aikrahguzar** [comment]
> PS - interesting performance detail of the formatted string:
> 
> In bibtex-completion, the candidate is a pre-forrnatted string; designed only for filtering, and NOT for display.
>
> The formatting for display happens on-demand, in ivy and helm, which both allow that.

I was thinking about this and this is the correct way to do it. Only a few strings need to be displayed at one time and formatting them on the fly will be instantaneous.

> Completing-read doesn't allow that, unless you count the new grouping support in Emacs 28. We use it already for multi-selection, BTW, and in a couple of other places. See, for example:

Grouping support was my idea of how to enable that too and it is used for multiple selection but there it just prioritizes so if completing read doesn't understand group functions, the user wouldn't be able to which entries are selected. That is pretty bad but not disastrous. Showing unformatted  entries seems much worse to me.

But I wonder if the `compat` library helps with that? I don't know if it just provides the new symbols to older emacs version or actually backports improvements to exisiting functions too. 

I think performance without caching probably hurts older and less powerful machines most. On my laptop even file with 1500 entries refreshes in under a second which is noticeable and somewhat annoying but too bad.

**Comment by bdarcus** [comment]
> But I wonder if the compat library helps with that? I don't know if it just provides the new symbols to older emacs version or actually backports improvements to exisiting functions too.

Somehow I doubt `group-function` would be something supported there. Completion seems not to get very much attention.

> I think performance without caching probably hurts older and less powerful machines most. On my laptop even file with 1500 entries refreshes in under a second which is noticeable and somewhat annoying but too bad.

To be clear, I'm not advocating removing caching; but it helps to evaluate the raw performance independent of it.

Bibtex-completion, for example, does caching as well, even with those optimizations.

**Comment by bdarcus** [comment]
After playing more this morning in https://github.com/emacs-citar/citar/pull/625#issuecomment-1146777923, tentative conclusions:

1. not a huge difference in performance creating lists vs hashes
2. the hash is _much_ faster to access in my ~1000 entry bib file
3. formatting the candidates is indeed more expensive, but it may not be a huge practical deal

I've not considered some of the other nuances yet, but might provide some useful info.

**Comment by bdarcus** [comment]
For some unknown reason (maybe because I haven't added new commit, but only force-pushed updates?), github won't let me reopen this.

But if either you want to play with this, the basic low-level stuff here works, at least to experiment with, or take a look at.

**Pull request closed without merging**
